<template>
    <div class="tw-flex tw-flex-col">
        <div class="tw-shadow-lg tw-bg-white tw-p-4 tw-flex tw-justify-between tw-mb-7">
            <div class="tw-font-bold tw-text-gray-700 tw-text-lg tw-py-1">Speech List</div>
            <q-btn color="green" icon="add" label="Add New" @click="showCreateSpeechModal"></q-btn>
        </div>

        <div class="tw-flex-grow">
            <div class="tw-shadow-lg tw-bg-white tw-p-4">
                <ec-table
                    :rows="mappedSpeeches"
                    :columns="columns"
                    :bodyCelTemplate="bodyCelTemplate"
                    @handleEdit="showEditSpeechModal($event)"
                    @handleDelete="showConfirmDeleteModal($event)"
                >
                    <template v-slot:cell-intent="slotProps">
                        <q-badge v-if="slotProps.row.intent" color="green" class="text-italic">
                            @{{ slotProps.row.intent.tag }}
                            <q-tooltip class="" anchor="center right" :offset="[50, 14]">
                                {{ slotProps.row.intent.description }}
                            </q-tooltip>
                        </q-badge>
                    </template>

                    <template v-slot:cell-generated_by="slotProps">
                        <div>
                            {{ slotProps.row.generated_by ?? 'Me' }}
                        </div>
                    </template>

                    <template v-slot:cell-forced_intent="slotProps">
                        <div>
                            <q-badge :color="slotProps.row.forced ? 'green' : 'orange'">
                                {{ slotProps.row.forced }}
                            </q-badge>
                        </div>
                    </template>

                    <template v-slot:cell-speech_in_ai="slotProps">
                        <div>
                            <q-badge :color="slotProps.row.has_in_ai ? 'green' : 'orange'">
                                {{ slotProps.row.has_in_ai }}
                            </q-badge>
                        </div>
                    </template>

                    <template v-slot:action-at-middle="slotProps">
                        <q-btn icon="settings" text-color="green" size="sm" dense flat>
                            <q-menu>
                                <div class="row no-wrap q-pa-md">
                                    <div class="column">
                                        <div class="text-h7 q-mb-md">Settings</div>
                                        <q-toggle
                                            @click="changeSpeechActiveStatus(slotProps.row)"
                                            v-model="slotProps.row.active"
                                            label="Status"
                                        />
                                    </div>
                                </div>
                            </q-menu>
                        </q-btn>
                    </template>
                </ec-table>
            </div>
        </div>

        <add-edit-speech-form
            :showAddEditSpeechModal="showAddEditSpeechModal"
            :updateModal="updateModal"
            :selectedForEditData="selectedForEditData"
            @createdSpeech="getSpeeches"
            @updatedSpeech="handleUpdatedSpeech"
            @hideModal="handleAddEditSpeechHideModal"
        />

        <delete-confirm-modal v-if="showDeleteModal" @confirmDelete="deleteSpeech" @hide="showDeleteModal = false" />
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import AddEditSpeechForm from 'pages/subscriber/speech-recognition/AddEditSpeechForm.vue';
import DeleteConfirmModal from 'components/common/modal/DeleteConfirmModal.vue';
import EcTable from 'components/common/table/EcTable.vue';

export default defineComponent({
    components: { EcTable, DeleteConfirmModal, AddEditSpeechForm },
    data(): any {
        return {
            columns: [
                { name: 'speech', align: 'left', label: 'Speech', field: 'speech' },
                {
                    name: 'intent',
                    align: 'center',
                    label: 'Mapped to Intent',
                    field: 'intent',
                },
                {
                    name: 'confidence',
                    align: 'center',
                    label: 'Confidence Level',
                    field: 'confidence',
                },
                {
                    name: 'generated_by',
                    align: 'center',
                    label: 'Generated By',
                    field: 'generated_by',
                },
                {
                    name: 'speech_in_ai',
                    align: 'center',
                    label: 'Speech in AI',
                    field: 'speech_in_ai',
                },
                {
                    name: 'forced_intent',
                    align: 'center',
                    label: 'Forced Intent',
                    field: 'forced_intent',
                },
                {
                    name: 'status',
                    label: 'Status',
                    field: 'status',
                    align: 'center',
                },
                {
                    name: 'action',
                    label: 'Actions',
                    field: 'action',
                    align: 'center',
                },
            ],
            // dynamicVariables: [
            //     { name: 'user_name', des: 'will print assigned name else guest' },
            //     { name: 'user_id', des: 'will print logged users id' },
            // ],
            bodyCelTemplate: {},
            speeches: [],
            showAddEditSpeechModal: false,
            updateModal: false,
            selectedForEditData: {},
            deleteSpeechId: '',
            showDeleteModal: false,
            newSpeechIntent: '',
            variableListModal: false,
        };
    },

    mounted() {
        this.getSpeeches();
    },

    computed: {
        mappedSpeeches(): any {
            return this.speeches.map((speech: any) => {
                speech.status = speech.active ? 'active' : 'Inactive';
                return speech;
            });
        },
    },

    methods: {
        getSpeeches() {
            this.$store
                .dispatch('speech/getSpeeches')
                .then((res: any) => {
                    this.speeches = res.data;
                })
                .catch((err: any) => {
                    console.log(err);
                });
        },

        showCreateSpeechModal() {
            this.showAddEditSpeechModal = true;
            this.updateModal = false;
        },

        showEditSpeechModal(speech: any) {
            this.updateModal = true;
            this.showAddEditSpeechModal = true;
            this.selectedForEditData = speech;
        },

        handleUpdatedSpeech($event: any) {
            const updatedSpeech = $event;

            const speechIndex = this.speeches.findIndex((speech: any) => speech.id === updatedSpeech.id);

            this.speeches[speechIndex] = updatedSpeech;
        },

        changeSpeechActiveStatus(speech: any) {
            this.$store
                .dispatch('speech/changeIntentActiveStatus', {
                    id: speech.id,
                    active: speech.active,
                })
                .then((res: any) => {
                    const speechIndex = this.speeches.findIndex((speech: any) => speech.id === res.data.id);

                    this.speeches[speechIndex] = res.data;

                    this.$helpers.showSuccessNotification(this, 'Speech active status change successful');
                })
                .catch((err: any) => {
                    this.$helpers.showErrorNotification(this, err.response.data.message);
                });
        },

        showConfirmDeleteModal(speech: any) {
            this.showDeleteModal = !this.showDeleteModal;
            this.deleteSpeechId = speech.id;
        },

        deleteSpeech() {
            this.$store
                .dispatch('speech/deleteSpeech', {
                    id: this.deleteSpeechId,
                })
                .then(() => {
                    this.showDeleteModal = false;
                    this.getSpeeches();

                    this.$helpers.showSuccessNotification(this, 'Speech deleted successful');
                })
                .catch((err: any) => {
                    this.$helpers.showErrorNotification(this, err.response.data.message);
                });
        },

        handleAddEditSpeechHideModal() {
            this.showAddEditSpeechModal = false;
            this.selectedForEditData = {};
        },
    },
});
</script>
